baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Ottemo Developer Documentation"
theme = "docdock"
# themesdir = "../.."

[params]
editURL = "https://github.com/ottemo/developer.ottemo.io/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ottemo/developer.ottemo.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-code'></i> API Documentation"
url = "https://swaggerhub.com/apis/Ottemo/foundation/1"
weight = 11


[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Contributors"
url = "/contributors"
weight = 30
